backend:
  name: github
  repo: liamfiddler/nextjs-sveltiacms
  branch: main

local_backend: true

publish_mode: editorial_workflow

media_folder: public/images
public_folder: /images

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: projects
    label: Projects
    folder: content/projects
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Year', name: 'year', widget: 'string' }
      - { label: 'Role', name: 'role', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
